### ISSUE TITLE
Packaging/Release Improvements Parent Issue

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/packaging#500]
(To make the process safer and faster)

### Important to have:
- [x] https://github.com/citusdata/packaging/issues/512 (package-builder ol/7 docker image cannot be built)
- [x] Add ability to run regression tests for generated images.
Lastly, we had lots of crashes in for debian/buster due to integer overflow. If we can add this ability, we could detect such crashes before deploying packages to packagecloud. (https://github.com/citusdata/packaging/pull/1171)
- [x] Add ability to filter the warnings we get when generating packages for some os's.
This could reduce the effort we spend when reviewing ci jobs, so it can help us to detect important warnings.
- [x] Add debug packages for the ones that we don't have now.
It would make debugging the crashes from our customers easier and it would save lots of "engineer x time" effort.
- [x] Fix https://github.com/citusdata/packaging/issues/352 (safety)

----------------------

### Nice to have:
- [x] Refactor packaging scripts. Maybe reimplement the tooling in a more readable language such as python. At least, refactor the existing scripts.
