### ISSUE TITLE
PG13 support in packaging pipeline

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/packaging#535]
### Citus: ###
- [x] Merge https://github.com/citusdata/packaging/pull/537 to fix #536 for community
- [x] Merge https://github.com/citusdata/packaging/pull/538 to fix #536 for enterprise 

### Other products: ###
* Other products should also resolve #536 for them

### All products: ###
- [x] Merge #532 & #541 to push package builder docker images for pg13.
- [x] Merge https://github.com/citusdata/tools/pull/82 & https://github.com/citusdata/tools/pull/83 to complete the changes that above pr's bring in tools repo in a hacky way.

### Citus ###
- [x] Merge https://github.com/citusdata/packaging/pull/544 to make https://github.com/citusdata/tools/pull/82 effective for community
- [x] Merge d98b160f6558221d1de4a38e618c322339d42fd4 together with 9.5.0 community (#542)
- [x] Merge 2857a4bb3087b0bf75808b28233da0f952af1aea together with 9.5.0 pgxn (#543)
- [x] Merge https://github.com/citusdata/packaging/pull/545 for installation scripts given in our docs, after releasing packages

### Other products: ###
* Other products should also use latest version of tools repo like in https://github.com/citusdata/packaging/pull/544
* Other products should also have a one-liner change like in d98b160f6558221d1de4a38e618c322339d42fd4

## A note on unsupported distros for pg13 for all products: ## 
Following distros don't have pg13 packages yet, so for now, we will skip docker image building (and **so distro package building**) for them:
* el/6
* ol/6
* debian/jessie

After those distros start supporting pg13, do below:
* Revert 4b2929fbeda21e7bdf14a1dbd81e6e1cf52bfd7f
* Revert a67a1110d7b29c70f1c859ffe300d5a42c4c1375

and run `update_dockerfiles.pl`. Also:

* Revert https://github.com/citusdata/tools/commit/da5ebdd18847f37d625d1c6db5027a166decd686
* Revert https://github.com/citusdata/tools/commit/ad42ab9ccc78a00bbb0c5e23ee8e12fdd9875ca2
and tag tools/master and start using new version of tools

## A note on Citus pg13 docker images: ## 

As we didn't release pg13 for topn & hll yet, we couldn't include them in our citus docker images, so disabled installing them.

After releasing packages for them:
- [x] Merge https://github.com/citusdata/docker/pull/203 to revert https://github.com/citusdata/docker/commit/e9751947058235cd6dc014c17fd70bb2a9e26115
