### ISSUE TITLE
Citus release checklist - [v10.1.4]

### ISSUE THREAD

**Issue by gurkanindibay** [citusdata/packaging#872]
## Several things to note here

These instructions assume you have `$VERSION`, `$PROJECT`, and `$REPO` environment variables set in your shell (e.g. `10.0.2`, `citus`, and `citus`). With those set, code from most steps can be copy-pasted.

**After this checklist, you're still not done: open a release checklist for Enterprise too!**

# Update OS Packages
## Debian and RedHat
- Change your directory to `packaging` repository directory & checkout `all-$PROJECT` branch.
- [x] Run the pipeline using branch name as all-citus https://github.com/citusdata/packaging/actions/workflows/update_package_properties.yml. Input tag name and if version is fancy, input the fancy version_no. Other parameters could be kept as is if you want
  - Then check the following (needed for both debian & redhat):
    - [x] Updated `pkglatest` variable in the `pkgvars` file to `$VERSION.citus-1`
  - Then check the following (needed for debian):
    - [x] A new entry (`$VERSION.citus-1`, `stable`) is added to the `debian/changelog` file
  - Then check the following (needed for redhat):
    - [x] `$PROJECT.spec` file is updated:
      - [x] `Version:` field
      - [x] `Source0:` field
      - [x] A new entry (`$VERSION.citus-1`) in the `%changelog` section
- [x] Get changes reviewed; merge the PR
- [x] Ensure Github Actions builds completed successfully and package count for each os is as below table and packages in postgres versions is compliant with `postgres-matrix.yml` in the `all-project` branch
